# Power Platform Managed Solution Deployment
# This workflow exports from dev, builds a managed solution, and deploys to production
# No post-deployment agent configuration is performed

name: Power Platform Managed Solution Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - test

# Repository Secrets Required:
# - DEV_ENVIRONMENT_URL: Development environment URL (e.g., https://yourorg-dev.crm.dynamics.com)
# - PROD_ENVIRONMENT_URL: Production environment URL (e.g., https://yourorg.crm.dynamics.com)
# - POWER_PLATFORM_SP_APP_ID: Service principal Application (client) ID
# - POWER_PLATFORM_SP_CLIENT_SECRET: Service principal client secret
# - POWER_PLATFORM_TENANT_ID: Azure AD tenant ID

env:
  SOLUTION_NAME: 'TestAutomationSolution'  # Replace with your actual solution name
  SOLUTION_EXPORTED_FOLDER: 'out/exported/'
  SOLUTION_FOLDER: 'out/solutions/'
  SOLUTION_TARGET_FOLDER: 'solutions/'

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export solution from development
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.POWER_PLATFORM_SP_APP_ID }}
        client-secret: ${{ secrets.POWER_PLATFORM_SP_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWER_PLATFORM_TENANT_ID }}
        solution-name: ${{ env.SOLUTION_NAME }}
        solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
        managed: false

    - name: Unpack solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
        solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ env.SOLUTION_NAME }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Upload exported solution as artifact
      uses: actions/upload-artifact@v4
      with:
        name: exportedsolution
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}

    - name: Upload unpacked solution as artifact
      uses: actions/upload-artifact@v4
      with:
        name: unpackedsolution
        path: ${{ env.SOLUTION_FOLDER }}

  build-managed-solution:
    needs: [ export-from-dev ]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Download exported solution artifact
      uses: actions/download-artifact@v4
      with:
        name: exportedsolution
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}

    - name: Setup Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Verify exported solution
      shell: pwsh
      run: |
        Write-Host "=== Verifying Exported Solution ==="
        Write-Host "SOLUTION_EXPORTED_FOLDER: ${{ env.SOLUTION_EXPORTED_FOLDER }}"
        Write-Host "SOLUTION_NAME: ${{ env.SOLUTION_NAME }}"
        
        $exportedSolutionPath = "${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}.zip"
        if (Test-Path $exportedSolutionPath) {
          Write-Host "✅ Found exported solution: $exportedSolutionPath"
          Write-Host "   File size: $((Get-Item $exportedSolutionPath).Length) bytes"
        } else {
          Write-Error "❌ Exported solution not found at: $exportedSolutionPath"
          exit 1
        }

    - name: Convert to managed solution
      shell: pwsh
      run: |
        Write-Host "=== Converting Solution to Managed ==="
        $exportedSolutionPath = "${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}.zip"
        $managedSolutionPath = "${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}_managed.zip"
        $tempUnpackFolder = "temp_unpack"
        
        try {
          Write-Host "Converting $exportedSolutionPath to managed..."
          
          # Unpack the unmanaged solution
          Write-Host "Step 1: Unpacking unmanaged solution..."
          pac solution unpack --zipfile $exportedSolutionPath --folder $tempUnpackFolder --packagetype Unmanaged
          
          # Pack as managed solution
          Write-Host "Step 2: Packing as managed solution..."
          pac solution pack --zipfile $managedSolutionPath --folder $tempUnpackFolder --packagetype Managed
          
          if (Test-Path $managedSolutionPath) {
            Write-Host "✅ Managed solution created successfully: $managedSolutionPath"
            Write-Host "   File size: $((Get-Item $managedSolutionPath).Length) bytes"
          } else {
            throw "Failed to create managed solution"
          }
        }
        catch {
          Write-Error "❌ Error during solution conversion: $_"
          exit 1
        }
        finally {
          # Clean up temp folder
          if (Test-Path $tempUnpackFolder) {
            Remove-Item $tempUnpackFolder -Recurse -Force
            Write-Host "Cleaned up temporary folder"
          }
        }

    - name: Upload managed solution as artifact
      uses: actions/upload-artifact@v4
      with:
        name: managedsolution
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}_managed.zip

  deploy-to-production:
    needs: [ build-managed-solution ]
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment: production

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Download managed solution artifact
      uses: actions/download-artifact@v4
      with:
        name: managedsolution
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}

    - name: Setup Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Verify managed solution before deployment
      shell: pwsh
      run: |
        Write-Host "=== Pre-Deployment Verification ===" -ForegroundColor Cyan
        $managedSolutionPath = "${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}_managed.zip"
        
        if (Test-Path $managedSolutionPath) {
          Write-Host "✅ Managed solution found: $managedSolutionPath" -ForegroundColor Green
          Write-Host "   File size: $((Get-Item $managedSolutionPath).Length) bytes" -ForegroundColor Gray
          Write-Host "   Target environment: ${{ secrets.PROD_ENVIRONMENT_URL }}" -ForegroundColor Gray
        } else {
          Write-Error "❌ Managed solution not found at: $managedSolutionPath"
          exit 1
        }

    - name: Deploy managed solution to Production
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ secrets.PROD_ENVIRONMENT_URL }}
        app-id: ${{ secrets.POWER_PLATFORM_SP_APP_ID }}
        client-secret: ${{ secrets.POWER_PLATFORM_SP_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWER_PLATFORM_TENANT_ID }}
        solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}_managed.zip
        force-overwrite: true
        publish-changes: true
        skip-dependency-check: false

    - name: Deployment success notification
      shell: pwsh
      run: |
        Write-Host "🎉 ===== DEPLOYMENT COMPLETED SUCCESSFULLY ===== 🎉" -ForegroundColor Green
        Write-Host ""
        Write-Host "📋 Deployment Summary:" -ForegroundColor Cyan
        Write-Host "   Solution Name: ${{ env.SOLUTION_NAME }}" -ForegroundColor White
        Write-Host "   Solution Type: Managed Solution" -ForegroundColor White
        Write-Host "   Target Environment: ${{ secrets.PROD_ENVIRONMENT_URL }}" -ForegroundColor White
        Write-Host "   Deployment Status: ✅ Success" -ForegroundColor Green
        Write-Host ""
        Write-Host "🔗 Next Steps:" -ForegroundColor Cyan
        Write-Host "   1. Verify solution components in the production environment" -ForegroundColor Yellow
        Write-Host "   2. Test functionality to ensure everything works as expected" -ForegroundColor Yellow
        Write-Host "   3. Configure any manual post-deployment settings if needed" -ForegroundColor Yellow
        Write-Host "   4. Update documentation with deployment details" -ForegroundColor Yellow

  run-solution-checker:
    needs: [ export-from-dev ]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Download exported solution artifact
      uses: actions/download-artifact@v4
      with:
        name: exportedsolution
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}

    - name: Setup Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Run Solution Checker
      uses: microsoft/powerplatform-actions/check-solution@v1
      with:
        environment-url: ${{ secrets.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.POWER_PLATFORM_SP_APP_ID }}
        client-secret: ${{ secrets.POWER_PLATFORM_SP_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWER_PLATFORM_TENANT_ID }}
        path: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
        checker-logs-artifact-name: 'solution-checker-logs'
